### ISSUE TITLE
Autodrive is too fast and broken on Linux curses builds

### ISSUE THREAD

**Issue by ghost** [Coolthulhu/Cataclysm-DDA#4658]
### Describe the bug

Autodrive in curses Linux build is almost completely broken in recent builds.

1. It is much faster now and screen is jumping around like crazy (because vehicle speed is constantly jumping between 0-64 and viewpoint is being adjusted). Previously it was kinda ok, no it is just painful to watch. Plus because of such speed it is almost impossible to see objects/monsters around and stop autodriving when needed...
2. Vehicle is **very** frequently crashing in things. Previously preventive collision detection was working, now if you use autodrive - you will get your vehicle trashed in just a day. Previously I was using autodrive almost always and was happy, now I am just afraid to use it.

It started behaving like this in past month, so I suspect https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4535 . If it is really a root cause - is it possible to make max speed for autodrive configurable at least and not hardcode it?

@yay855 , @chaosvolt FYI ^

### Steps To Reproduce

1. Use Linux curses build with similar terminal size.
2. Use autodrive (try to use it for few days and you will see how bad it is now).

### Versions and configuration

cbn-linux-curses-x64-2024-05-15.tar.gz on Arch / rxvt-unicode.

Terminal resolution:
```
echo $(tput cols)x$(tput lines)

158x43 
```

**Comment by Ignaramico** [comment]
the recent builds have the option to change the auto drive speed. and wasnt this kinda bug already solved in  #4677 . As of today i use linux, and it works ok.
